### ISSUE TITLE
something went wrong when categories number is modified.

### ISSUE THREAD

**Issue by Oneplus** [wpm/Naive-Bayes-Gibbs-Sampler#1]
I have just modified number of categories, vocabulary size and number of documents in **main** as

```
    categories = 3      # number of categories
    vocabulary = 5      # vocabulary size
    documents = 7       # dataset size
```

and this code break down, i think `estimated_labels = zeros(self._categories(), int)` in `estimate_labels` may be `estimated_labels = zeros(self._documents(), int)`

**Comment by wpm** [comment]
Fixed in 285e4417d59af7a0d9e58a493225eb3e3fc40488.

Good catch. Thanks.
